export const ACTIONS = {
    ADD_PROVIDER_REQUEST: "ADD_PROVIDER_REQUEST",
    ADD_PROVIDER_FAILED: "ADD_PROVIDER_FAILED",
    ADD_PROVIDER_SUCCESS: "ADD_PROVIDER_SUCCESS",
    LIST_PROVIDERS_REQUEST: "LIST_PROVIDERS_REQUEST",
    LIST_PROVIDERS_FAILED: "LIST_PROVIDERS_FAILED",
    LIST_PROVIDERS_SUCCESS: "LIST_PROVIDERS_SUCCESS",
}
