export const ACTIONS = {
    ADD_ARTICLE_REQUEST: "ADD_ARTICLE_REQUEST",
    ADD_ARTICLE_FAILED: "ADD_ARTICLE_FAILED",
    ADD_ARTICLE_SUCCESS: "ADD_ARTICLE_SUCCESS",
    ADD_PROVIDER_REQUEST: "ADD_PROVIDER_REQUEST",
    ADD_PROVIDER_FAILED: "ADD_PROVIDER_FAILED",
    ADD_PROVIDER_SUCCESS: "ADD_PROVIDER_SUCCESS",
    LIST_ARTICLES_REQUEST: "LIST_ARTICLES_REQUEST",
    LIST_ARTICLES_FAILED: "LIST_ARTICLES_FAILED",
    LIST_ARTICLES_SUCCESS: "LIST_ARTICLES_SUCCESS",
    LIST_PROVIDERS_REQUEST: "LIST_PROVIDERS_REQUEST",
    LIST_PROVIDERS_FAILED: "LIST_PROVIDERS_FAILED",
    LIST_PROVIDERS_SUCCESS: "LIST_PROVIDERS_SUCCESS",
}
