version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: pszi_db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=api
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - api
  api:
    build: .
    container_name: pszi_api
    networks:
      - api
    depends_on:
      - mongo

volumes:
  mongodb:
  mongoconfig:

networks:
  api:
    driver: bridge
