version: '3.8'

services:
  db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pszi_info
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - pszi-info
  api:
    build: api/
    ports:
      - '8080:8080'
    networks:
      - pszi-info
    depends_on:
      - db
  ui:
    build: ui/
    ports:
      - '3080:80'
      - '3443:443'
    networks:
      - pszi-info
    depends_on:
      - api

volumes:
  dbdata:

networks:
  pszi-info:
    driver: bridge
