version: '3.8'

services:
  db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DATABASE}"
    volumes:
      - dbdata:/var/lib/postgresql/data
  api:
    image: csuvikg/pszi-info-api:latest
    ports:
      - '8080:8080'
    environment:
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "POSTGRES_DATABASE=${POSTGRES_DATABASE}"
      - "POSTGRES_USERNAME=${POSTGRES_USERNAME}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}"
    depends_on:
      - db
  ui:
    image: csuvikg/pszi-info-ui:latest
    environment:
      - "API_SCHEMA=${API_SCHEMA}"
      - "API_DOMAIN=${API_DOMAIN}"
      - "API_PORT=${API_PORT}"
    ports:
      - '3080:80'
      - '3443:443'
    depends_on:
      - api

volumes:
  dbdata:
