version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: pszi_db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=api
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb

volumes:
  mongodb:
  mongoconfig:
