spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/pszi_info
    username: postgres
    password: postgres
server:
  error:
    include-stacktrace: never
google-maps:
  geo-api-key: "${GOOGLE_MAPS_API_KEY}"
