spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/pszi_info
    username: postgres
    password: postgres
  profiles:
    include: secrets
server:
  error:
    include-stacktrace: never
