spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}"
    username: "${POSTGRES_USERNAME}"
    password: "${POSTGRES_PASSWORD}"
server:
  error:
    include-stacktrace: never
google-maps:
  geo-api-key: "${GOOGLE_MAPS_API_KEY}"
