name: Test and deploy frontend
'on':
  push:
    branches:
      - main
jobs:
  test-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
        working-directory: ./ui
      - run: npm run test
        working-directory: ./ui
        env:
          CI: true
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PSZI_INFO }}'
          channelId: live
          projectId: pszi-info
          entryPoint: "./ui"
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
