name: Test code
on: [push]
jobs:
  Test-Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Change into backend project root
        run: cd api
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
